;== PBX-NG pjsip.conf (estatico): transportes. Endpoints en realtime (DB) ==
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[transport-ws]
type=transport
protocol=ws
bind=0.0.0.0:8088
