listening-port=3478
fingerprint
lt-cred-mech
realm=@@TURN_REALM@@
user=@@TURN_USER@@:@@TURN_PASS@@
external-ip=@@TURN_EXT_IP@@
min-port=49152
max-port=65535
no-tls
no-dtls
#no-cli (cli habilitado por consola PBX-NG)
log-file=/var/log/turnserver.log
simple-log
cli-password=@@TURN_CLI_PASS@@
cli-ip=127.0.0.1
# --- PBXNG cuotas/seguridad (Turn-NG) ---
total-quota=200
stale-nonce=600
no-loopback-peers
no-multicast-peers
