[settings]
ps_endpoints => pgsql,pbxng,ps_endpoints
ps_auths => pgsql,pbxng,ps_auths
ps_aors => pgsql,pbxng,ps_aors
ps_domain_aliases => pgsql,pbxng,ps_domain_aliases
ps_endpoint_id_ips => pgsql,pbxng,ps_endpoint_id_ips
ps_contacts => pgsql,pbxng,ps_contacts
ps_registrations => pgsql,pbxng,ps_registrations
extensions => pgsql,pbxng,extensions
queues => pgsql,pbxng,queues
queue_members => pgsql,pbxng,queue_members
voicemail => pgsql,pbxng,voicemail
