;== PBX-NG pjsip.conf (estatico): transportes. Endpoints en realtime (DB) ==
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[transport-ws]
type=transport
protocol=ws
bind=0.0.0.0:8088

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060

[transport-tls]
type=transport
protocol=tls
bind=0.0.0.0:5061
cert_file=/etc/asterisk/keys/pbxng.crt
priv_key_file=/etc/asterisk/keys/pbxng.key
method=tlsv1_2

[global]
type=global
endpoint_identifier_order=username,ip,anonymous
